{% set name = "minimalkv" %}
{% set version = "1.2.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/minimalkv-{{ version }}.tar.gz
  sha256: 9a9a8205370a06ac65db1b9ec2dcd7cf4a37b76195f00ec63598a901646cec96

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools_scm
  run:
    - python >=3.6
    - uritools

test:
  imports:
    - minimalkv
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/data-engineering-collective/minimalkv
  summary: A key-value storage for binary data, support many backends.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - fjetter
    - mlondschien
    - siboehm
    - xhochy
