{% set name = "minimalkv" %}
{% set version = "1.1.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/minimalkv-{{ version }}.tar.gz
  sha256: 242659af1b2494beb1a98491cd50a9ce9b8403f0019c12aa9b099b1c431a57ef

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
    - setuptools_scm
  run:
    - python >=3.7

test:
  imports:
    - minimalkv
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/data-engineering-collective/minimalkv
  summary: A key-value storage for binary data, support many backends.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - fjetter
    - mlondschien
    - siboehm
    - xhochy
